Section "InputClass"
    Identifier "Yeti keyboard layout"
    MatchIsKeyboard "on"
    Option "XkbModel" "pc105"
    Option "XkbLayout" "yeti,ru,am"
    Option "XkbVariant" ",,phonetic"
    Option "XkbOptions" "compose:menu"
EndSection
