export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git)

source "$ZSH/oh-my-zsh.sh"

export PATH="$HOME/bin:$HOME/.local/bin:$HOME/.cargo/bin:$PATH"

if command -v direnv >/dev/null; then
  eval "$(direnv hook zsh)"
fi
